services:
  oracle-db:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-db
    env_file:
      - .env
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle_data:/opt/oracle/oradata

  dbgate:
    image: dbgate/dbgate
    ports:
      - "3000:3000"

volumes:
  oracle_data:
